#!/usr/bin/env bash

set -ex

yosys -g -l Top.rpt <<YOSYS
read_verilog -sv Top.sv
synth_ice40 -top top
write_json Top.json
YOSYS

nextpnr-ice40 --log Top.tim --up5k --package sg48 --json Top.json --pcf Top.pcf --asc Top.asc
icepack Top.asc Top.bin
iceprog Top.bin
