#!/usr/bin/env fish

fish_add_path /opt/homebrew/opt/llvm/bin
set CXX clang++
# set opt -O3
set opt

echo "
read_verilog -sv Top.sv
write_cxxrtl -header build/kalaturg.cc
" | yosys -q -


$CXX $opt \
    -DCLOCK_NAME=clock \
    -I. \
    -I(yosys-config --datdir)/include/backends/cxxrtl/runtime \
    -c cxxsim/main.cc \
    -o build/main.o

$CXX $opt \
    build/main.o \
    -o build/cxxsim


